name: Caller Workflow

on:
  push:

permissions:
  contents: read

jobs:
  ci:
    uses: ./.github/workflows/reusable.yaml
    with:
      node_version: "24"
      test_command: "npm run test:run"
      build_command: "npm run build"
  
  deploy:
    runs-on: ubuntu-latest
    needs: ci
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: prod-build-${{ needs.ci.outputs.build_version }}
      
      - name: Verify build
        run: ls -R

      - name: Show build versin
        run: "echo Build Version: ${{ needs.ci.outputs.build_version }}"