name: Conditional Flow

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Test cases passed"
    
  notify:
    runs-on: ubuntu-latest
    needs: test
    if: failure()
    steps:
      - run: echo "Test cases failed , sending notification"
