name: My First Workflow

on:
  push:

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: My Name
        run: echo "Gopal"
      
      - name : Topic 
        run : "Learning Github Actions"

      - name : Day
        run : "Day 1"