name: Github Token

on:
  push:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check Github Token
        run: |
          if [ -n "$GITHUB_TOKEN" ]; then
            echo "Github token exits"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
