name: Github Environments

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Show environment
        run: echo "The environment of app ${{ vars.APP_ENV }}"

      - name: Check enviroment secret
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          if [ -n "$API_KEY" ]; then
            echo "Key is available"
          else
            echo "Key is missing"
          fi