name: Github Environments

on:
  push

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: staging
    steps:
      - name: Show environment
        run: echo "The environment of app ${{ vars.APP_ENV }}"