name: Greet Automation

on:
  pull_request:
    branches:
      - main    

jobs:
  greet:
     runs-on: ubuntu-latest

     steps:
      - uses: actions/checkout@4

       - run: echo "Hell from AWS VPC REPO"