name: Matrix Flow

on:
  push:

jobs:
  ci:
    strategy:
      matrix:
        node-version: [22, 24]
        os: [ ubuntu-latest, windows-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Node js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      
      - name: Verify node version
        run: node --version
      
      - name: Install depdencies
        run: npm ci

      - name: Run test cases
        run: npm run test:run
    