name: Node CI

on: 
  push:

jobs: 
  build:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Verfity Code Checkout
        run: ls

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verfity Node installation
        run : node --version
        