name: Reusable workflow

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
      test_command:
        required: true
        type: string
      build_command:
        required: true
        type: string
    outputs:
      build_version:
        description: "Build version genreated by CI"
        value: ${{ jobs.ci.outputs.build_version }}

permissions:
  contents: read
  
jobs:
  ci:
    runs-on: ubuntu-latest
    outputs:
      build_version: ${{ steps.version.outputs.version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
      
      - name: Install dependencies
        run: npm ci
      
      - name: Run test cases
        run: ${{ inputs.test_command }}

      - name: Run build
        run: ${{ inputs.build_command }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: prod-build-${{ github.run_number }}
          path: dist/
          retention-days: 3
      
      - name: Generate Build Versin
        id: version
        run: echo "version=1.0.${GITHUB_RUN_NUMBER}" >> "$GITHUB_OUTPUT"
