name: GithHub Action Secrets

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      FAKE_SECRET: ${{ secrets.FIRST_SECRET }}
    steps:
      - name: Check the SECRET
        run: |
          if[ -n "$FAKE_SECRET" ]; then
              echo "secret is available"
          else
              echo "secret is missing"
          fi