name: Trouble Shooting

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Broken Command
        run: |
          echo "Starting"
          non-exist-command
          echo "Finished"